apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cartservice
  namespace: boutique
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cartservice
  namespace: boutique
subjects:
  - kind: ServiceAccount
    name: cartservice
    namespace: boutique
roleRef:
  kind: Role
  name: cartservice
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
  namespace: boutique
secrets:
  - name: cartservice
---
apiVersion: v1
kind: Secret
metadata:
  name: cartservice
  namespace: boutique
  annotations:
    kubernetes.io/service-account.name: cartservice
type: kubernetes.io/service-account-token
